### ISSUE TITLE
Is it possible to use this with your Processing 4 Maven link?

### ISSUE THREAD

**Issue by proffparadox** [micycle1/ProcessingFX#5]
Hi, I'm abusing the issue's section a little bit as I wasn't sure how to contact, is it possible to use this without downloading a modified core.jar, or by using a maven repo?/ does processing 4 effect it in any way?

I'm currently writing a genetic algorithm in Java and using Processing to render it but I want to drop the processing Papplet into a JavaFX gui to make it into something that resembles an actual program, I'd also like to be able to use this for a future project, are you able to point me in the right direction on doing this?

**Comment by micycle1** [comment]
My Processing 4 core maven project wouldn't work, since the JavaFX parts are still `protected`, and they need to be `public` to launch via a custom .FXML file (someone created a PR for this at https://github.com/processing/processing/pull/6051 but it's yet to be merged).

You'll be pleased to know that I've included a small `.pde` project in this repo (https://github.com/micycle1/ProcessingFX/blob/master/ProcessingFX.pde) that switches in the FXML stage **after** Processing loads -- this does not require the modified `core.jar`.

**Comment by micycle1** [comment]
Alternatively you could make the same changes as I did to the source code for processing-core, create a GitHub maven repo out of it, and then host the modified processing-core as a Maven dependency via Jitpack.

**Comment by proffparadox** [comment]
Ah, okay, that gives me something to go on, thanks for the help, not sure I even would know where to begin with your modifications to Processing, but your (https://github.com/micycle1/ProcessingFX/blob/master/ProcessingFX.pde) looks very helpful and I should be able to implement that.

**Comment by micycle1** [comment]
> I even would know where to begin with your modifications to Processing

You can take a look in the modified core.jar or at that PR. Even I've forgotten exactly what I did by now.
